baseURL = "https://goldfish0506.github.io/"
languageCode = "en"
DefaultContentLanguage = "zh"
author = "Kim"
paginate = 20
ignoreErrors = ["error-remote-getjson"]
enableInlineShortcodes = true

title = "ğŸ”­ äººé—´æŒ‡å—"
theme = "paper"

[params]
  color = 'linen'
  twitter = 'Goldfish0506'
  github = 'Goldfish0506'
  rss = true

  avatar = 'goldfish.jinyu@gmail.com'
  name = 'ä¸»ç¼– Kim'
  bio = 'å°†è‡ªå·±çš„ç²¾ç¥ï¼Œæ³¨å…¥äº§å“ä¸æ–‡å­—ä¸­'
  
  # misc
  disableHLJS = true
  math = true            
  monoDarkIcon = true

# é…ç½®ç½‘ç«™èœå•
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10
